	</div>
	<div id='footer'>
		<div class='logo'><a href='<?= $this->pageURL() ?>'>ScheduleMaker</a></div>
		<div class='csh'>
			<a href="http://www.csh.rit.edu/"><img src="<?= $this->imgURL('csh.png') ?>" alt="CSH" /></a>
		</div>
		<div class='nav'>
			<a href='<?= $this->pageURL("generate") ?>'>Build Schedules</a> | 
			<a href='<?= $this->pageURL("browse") ?>'>Browse Courses</a> | 
			<a href='<?= $this->pageURL("roulette") ?>'>Course Roulette</a> | 
			<a href='<?= $this->pageURL("status") ?>'>Status</a>
		</div>
		<div>
			Idea: John Resig (phytar at csh.rit.edu)<br />
			Development: Ben Russell (benrr101 at csh.rit.edu)<br />
			Hosting: <a href="http://www.csh.rit.edu/">Computer Science House</a><br />
			Uses <a href="http://somerandomdude.com/work/iconic/">iconic icon set by P.J. Onori</a>, 
			licensed under <a href="http://creativecommons.org/licenses/by-sa/3.0/us/">CC BY-SA 3.0</a>
		</div>
	</div>
	</div>
</body>
</html>
