	<div id="mainMenu">
		<div class='navItem'>
			<a href='generate.php'><img src='img/calendar.png' alt='Make a Schedule'></a>
			<div><a href='generate.php'>Make a Schedule</a></div>
		</div>
		<div class='navItem'>
			<a href='browse.php'><img src='img/browse.png' alt='Browse Courses'></a>
	
			<div><a href='browse.php'>Browse Courses</a></div>
		</div>
		<div class='navItem'>
			<a href='roulette.php'><img src='img/roulette.png' alt='Course Roulette'></a>
			<div><a href='roulette.php'>Course Roulette</a></div>
		</div>
	</div>
