	<div id="mainMenu">
		<div class='navItem'>
			<a href='<?= $this->pageURL('generate') ?>'>
				<img src='<?= $this->imgURL('calendar.png') ?>' alt='Make a Schedule'>
			</a>
			<div><a href='<?= $this->pageURL('generate') ?>'>Make a Schedule</a></div>
		</div>
		<div class='navItem'>
			<a href='<?= $this->pageURL('browse') ?>'>
				<img src='<?= $this->imgURL('browse.png') ?>' alt='Browse Courses'>
			</a>
			<div><a href='<?= $this->pageURL('browse') ?>'>Browse Courses</a></div>
		</div>
		<div class='navItem'>
			<a href='<?= $this->pageURL('roulette') ?>'>
				<img src='<?= $this->imgURL('roulette.png') ?>' alt='Course Roulette'>
			</a>
			<div><a href='<?= $this->pageURL('roulette') ?>'>Course Roulette</a></div>
		</div>
	</div>
